### ISSUE TITLE
Package name is documented as `zapr` but is actually `zaplogr`

### ISSUE THREAD

**Issue by grantr** [go-logr/zapr#1]
Code importing this is confusing because the import path is `github.com/go-logr/zapr` but the imported package is`zaplogr`. See https://github.com/kubernetes-sigs/controller-runtime/pull/71#issuecomment-403989177.

**Comment by mengqiy** [comment]
cc: @DirectXMan12

**Comment by DirectXMan12** [comment]
whoops, I must have made a typo when moving it.  I'll fix that right now
