### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by dan-j** [go-logr/zapr#12]
Just came here to report #6 but notice it's been fixed, just the change hasn't been release under a new tag.

Go Modules will by default install v0.1.1 which doesn't have these changes.

Workaround for now is to `go get github.com/go-logr/zapr@master`, but many people won't do this by default.

Could v0.1.2 be created?

**Comment by mattysweeps** [comment]
A new release still could be tagged, and it would be even better if first used a new tag from `github.com/go-logr/logr` (https://github.com/go-logr/logr/issues/22)
