### ISSUE TITLE
"stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error

### ISSUE THREAD

**Issue by hhannani** [go-logr/zapr#23]
Team,

We have been facing this error while deploying OPA-Gatekeeper policies, Please feel free to close this issue if you think it is not related to this project.

resource","metaKind":"upgrade","name":"allow-only-ecr-registry","namespace":"","error":"Operation cannot be fulfilled on k8sallowedrepos.constraints.gatekeeper.sh "allow-only-ecr-registry": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error

**Comment by hhannani** [comment]
@tamalsaha @DirectXMan12 any insight on this issue, would be appreciated.

**Comment by avdhoot** [comment]
@hhannani might help --> https://github.com/kubernetes-sigs/kubebuilder/issues/1593

**Comment by thockin** [comment]
Can you show exactly how you set up your zap logger that you pass into zapr, and what the log-line looks like?
