### ISSUE TITLE
Incorrect number of arguments detected

### ISSUE THREAD

**Issue by kwiromeo** [go-logr/zapr#32]
**Some Background**:
I've been trying to create a top level logger for an application using zap, and zapr.
The api I am aiming for is something along the lines of this:
- `log.Debug(msg, "key 1", "value 1")`
- `log.Info(msg, "key 2", "value 2")`
Whenever I attempt to do this, I get the error `odd number of arguments passed as key-value pairs for logging`

**Code to reproduce error**

Here's some sample code to reproduce the error:

```go
package main

import (
	"github.com/go-logr/logr"
	"github.com/go-logr/zapr"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
	"os"
)

func NewZaprLogger() logr.Logger {

	consoleWriterSyncer := zapcore.AddSync(os.Stderr)
	logConsoleEnc := zapcore.NewConsoleEncoder(zap.NewDevelopmentEncoderConfig())

	levelSelector := zap.LevelEnablerFunc(func(lvl zapcore.Level) bool {
		return lvl >= zapcore.DebugLevel
	})

	logCore := zapcore.NewTee(zapcore.NewCore(logConsoleEnc, consoleWriterSyncer, levelSelector))

	zapLog := zap.New(logCore)

	logLocal := zapr.NewLogger(zapLog)

	return logLocal
}

func Debug(msg string, keysAndValues ...interface{}) {

	logger := NewZaprLogger()

	if keysAndValues != nil {
		logger.V(1).Info(msg, keysAndValues)
	} else {
		logger.V(1).Info(msg)
	}

}

func main() {
	Debug("this is a message", "key 1", "value 1")
}
```

Here's the output I get: 
```bash
2021-07-21T10:25:27.128-0400    DPANIC  odd number of arguments passed as key-value pairs for logging   {"ignored key": ["key 1","value 1"]}
2021-07-21T10:25:27.128-0400    DEBUG   this is a message
```
---
**Questions**:
- Is this a use case that is supported by Zapr?
- Do I need to initialize the logger differently to make it work?
---

I recognize that it's possible that my use case is not one supported by Zapr, but I wanted to ask before I changed my approach.

Any insights on this is greatly appreciated. 

Thanks!

**Comment by adracus** [comment]
In this line

```go
logger.V(1).Info(msg, keysAndValues)
```
You're calling `logr` with `keysAndValues` 'unspread', passing `[]interface{}` to your logger. You need to do

```go
logger.V(1).Info(msg, keysAndValues...)
```

to resolve the issue.

**Comment by kwiromeo** [comment]
Thanks @adracus!
That resolved it. I am coming from C++, so spread operators is new to me.
