### ISSUE TITLE
panic messages use keys with spaces

### ISSUE THREAD

**Issue by pohly** [go-logr/zapr#36]
The logr recommendation is to not use spaces in keys:

https://github.com/go-logr/logr/blob/622c97b4eb90a99cc628f4773662eb0015ce0f2a/logr.go#L128

zapr violates that recommendation with `zap field`, `ignored key`, `invalid key` in its panic messages in `handleFields.

**Comment by pohly** [comment]
Should and can those fields be renamed?

I've not seen a recommendation how to handle keys that consist of multiple words. `zapField` or `zap-field` or ... ?

**Comment by thockin** [comment]
I don't know if zap allows us to change these.  JSON allows keys with spaces, we just documented this as a convention for easiest consumption.  It's probably not very consequential.

**Comment by pohly** [comment]
That's in zapr.go, our own code. We could change the keys if we wanted to.

https://github.com/go-logr/zapr/blob/a3325063a2373b60193ce4cc7e47634dac8e2607/zapr.go#L93

**Comment by thockin** [comment]
I question the value of DPanic from within this lib.  Disallowing zap.Field is weird.  That's not our business.  Input errors should not generate additional log-lines IMO, though I can see value to "panic on ill-formed log-lines in debug mode"

**Comment by thockin** [comment]
But if we DO keep it, I think it's fine to change the keys.

Watch out or you'll end up a maintainer of this :)

**Comment by pohly** [comment]
> I question the value of DPanic from within this lib. Disallowing zap.Field is weird. That's not our business.

I'm on the edge myself. It breaks portability of the code which calling the logger with such a parameter, but perhaps someone doesn't care and/or wants to do it when knowing that the logger is a zap logger.

> Input errors should not generate additional log-lines IMO, though I can see value to "panic on ill-formed log-lines in debug mode"

I like the idea of making those panic messages conditional on a debug flag. Then the caller can decide.

@DirectXMan12 you originally wrote that code - any thoughts on this? ^^^

> But if we DO keep it, I think it's fine to change the keys.

That then begs the question: what should the non-space-using-keys be? nonSpaceUsingKeys? NonSpaceUsingKeys? We can discuss here and then extend the logr recommendations. IMHO that's actually more important than updating zapr because developers will loose time when encountering this issue without getting some guidance, for example because they start looking for prior art to remain consistent.

> Watch out or you'll end up a maintainer of this :)

Who, me? I have no idea what you are talking about. :grinning:

**Comment by thockin** [comment]
@DirectXMan12 has found themselves mostly detached from this code, so while I welcome their input, I wouldn't block on it for too long.

> nonSpaceUsingKeys? NonSpaceUsingKeys?

There's no convention that I know of.  Kubernetes chose `nonSpaceUsingKeys` and I hate it.  It has cause so many problems with Go's conventions and godoc comments.  If we have to pick I'd say "NonSpaceUsingKeys" or "non-space-using-keys"

**Comment by pohly** [comment]
>  Kubernetes chose nonSpaceUsingKeys and I hate it.

Where was that chosen?

> It has cause so many problems with Go's conventions and godoc comments

Because keys were confused with Go code, for example in search/replace? I don't like it either, I'm just trying to understand whether it is objectively worse than the alternatives.

> There's no convention that I know of.

Perfect, then we can recommend something.

> If we have to pick I'd say "NonSpaceUsingKeys" or "non-space-using-keys"

I like "non-space-using-keys" better because it is consistent with existing single-word keys which use lower case ("err", "v").

**Comment by thockin** [comment]
> Where was that chosen?

For all of our APIs - the canonical JSON and YAML is lowercaseUppercase

> Because keys were confused with Go code, for example in search/replace?

It requires every field has a `json` tag with the name (vector for cut-paste errors) and because comments can either be godoc compatible or useful in doc-gen but not both.

**Comment by pohly** [comment]
> For all of our APIs - the canonical JSON and YAML is lowercaseUppercase

I see. I thought it was something specific to JSON message output, perhaps in the structured logging KEP or one of the associated documents. IMHO we can ignore this Kubernetes API convention for JSON log messages. Or side-step the question entirely by proposing "non-space-using-keys"... I'll submit a PR.

**Comment by pohly** [comment]
I found that Kubernetes has a recommendation for multi-word keys. You won't like it. Let's continue the discussion in https://github.com/go-logr/logr/pull/65

**Comment by thockin** [comment]
Logr and zapr are not beholden to kubernetes decisions :)

**Comment by pohly** [comment]
They are not, but conflicting recommendations put developers into an awkward spot. I'd like to see more cooperation (see zapr fork), not less.

**Comment by pohly** [comment]
We added some recommendations to logr. We could change the keys accordingly here, but strictly speaking that might be an API break for zapr v1.0.0 (it could be that someone looks for the previous values), so let's keep everything as-is here. Simpler, too...
