### ISSUE TITLE
Why doesn't support semver spec to latest tag?

### ISSUE THREAD

**Issue by zchee** [go-logr/zapr#41]
Team,

I found a new release a few days and totally agreed on pin zap to v.19.0.
However, the latest `v1.0.0+1` release tag doesn't support semver spec.

Actually, This release tag replaced `v1.0.1-0.20210809170106-a3325063a237`, pkg.go.dev can't handle `+1` verb. See below:

- https://pkg.go.dev/github.com/go-logr/zapr@v1.0.0+1
- https://pkg.go.dev/github.com/go-logr/zapr@v1.0.1-0.20210809170106-a3325063a237

Is it intended?

**Comment by thockin** [comment]
I'm waiting for a few other PRs to land before tagging a new release.  I was trying to keep the main version in sync with logr itself, but I need another token to indicate this packages own version.

**Comment by thockin** [comment]
I sent a message to https://groups.google.com/g/golang-dev asking if this is supposed to work or not (+1 is valid semver)

**Comment by thockin** [comment]
Will rectify on next tag, and won't use the `+` notation any more.

**Comment by zchee** [comment]
@thockin Thanks for politely reply. I understand this background now.

> I sent a message to https://groups.google.com/g/golang-dev asking if this is supposed to work or not (+1 is valid semver)

I didn't know "+1 is valid semver", but I'm surprised go mod doesn't support all of semver spec.

> Will rectify on next tag, and won't use the + notation any more.

Thanks!

I'll closing this issue.
