### ISSUE TITLE
inconsistent logging of value vs. value embedded somewhere else

### ISSUE THREAD

**Issue by pohly** [go-logr/zapr#45]
When the value in a key/value pair is logged, it gets passed through [`zap.Any`](https://github.com/uber-go/zap/blob/eaeb0fc72fd23af7969c9a9f39e51b66827507ca/field.go#L413-L549) which uses certain interfaces (like `Stringer`) if available to serialize the value.

When that same value is contained in something else like a slice or a struct, it gets handled differently by `zap.Reflect`: those interfaces are ignored.

This is why `[]klog.ObjectRef` worked as intended (logged as array of structs) whereas `kobj.ObjectRef` didn't (logged as string).

I'm not sure whether this is a problem, but it seems inconsistent.

**Comment by thockin** [comment]
This seems like it  would be true for zap in general, no?

**Comment by pohly** [comment]
Yes, it seems to be how zap works. I'm still undecided whether I like it or not.
