### ISSUE TITLE
Logr to Zap Level Confusion

### ISSUE THREAD

**Issue by Spiderpig86** [go-logr/zapr#53]
Hi,

I'm trying to understand how I can use Logr to set the log levels for logging verbosity. I'm pretty new to this library and Zap in general, so I'll probably ask some pretty fundamental questions here.

My requirement is that I want to be able to show/hide logs depending on verbosity. For example, I want to set a setting in the logger to only show V(2) or above (in this case it is Warning and above for Zap).

The problem is that with using the `Logr` interface, the `V()` function only applies non-negative values. According to this StackOverflow post, all the levels from Logr are inverted in Zap. This means to use the Warning level in Zap, I must pass in `V(-2)`. However, this is not possible given that the function implementation applies all negative values as 0: https://github.com/go-logr/logr/blob/master/logr.go#L282-L292

Is it correct my understanding of the mapping is this:

|Logr|Zap|
|---|---|
|1|-1 (Debug)|
|0|0 (Info)|
|-1|1 (Warning)|
|-2|2 (Error)|

and so on...

How can I set negative verbosity levels if I am restricted to only using the Logr interface?

Thanks

**Comment by pohly** [comment]
As you noticed, you cannot do `logger.V(-1)` to emit a warning. The concept of "warning" doesn't exist in logr, there are just "info" messages of different verbosity, with 0 always getting printed. If you want to flag an info message as "warning", you can put that into the wording of the message.

The zap error level is used when you use `logger.Error`. Note that passing an `error` is optional, so you can do `logger.Error(nil, "something really bad happened")`.

**Comment by Spiderpig86** [comment]
Thanks for the explanation! I guess this is something that is ingrained in Logr's core design.

**Comment by thockin** [comment]
You can use arbitrary (up to 127) V levels, just not zap's "warning".

https://github.com/go-logr/zapr/blob/master/example/main.go#L42-L45
