### ISSUE TITLE
Wrong line reported

### ISSUE THREAD

**Issue by robfig** [go-logr/zapr#6]
Running the example program from the README prints this line:

```
2019-08-08T11:36:25.528-0400	INFO	zapr/zapr.go:69	Logr in action!	{"the answer": 42}
```

I would expect it to print the file and line of the program, rather than a line within zapr.go.

**Comment by abursavich** [comment]
Yep, I was coming here to file the same issue. Zapr changes the call stack, but doesn't use the AddCallerSkip option to adjust the frames to the caller. 

Example: https://play.golang.org/p/VdTPtGsGXSC

**Comment by ralf-cestusio** [comment]
This does fix it for the exact bug reportet, but does break again when using WithName or WithValues since those are not supposed to add an additional skip .
